# cf https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "sentry-ruby"
        versions: ["5.x"]
      - dependency-name: "sentry-rails"
        versions: ["5.x"]
      - dependency-name: "sentry-sidekiq"
        versions: ["5.x"]
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@sentry/browser"
        versions: ["7.x"]
      - dependency-name: "@sentry/tracing"
        versions: ["7.x"]
      - dependency-name: "@sentry/cli"
        versions: ["2.x"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
