require:
  - rubocop-rails

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "db/**/*"
    - "shared/db/**/*"
    - "config/db/*"
    - "config/environments/*"
    - "config/initializers/*"
    - "lib/tasks/**/*"
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/MultilineMethodCallIndentation:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - spec/**/*
    - app/lib/demos/**/*
