backend:
  name: github
  repo: betagouv/collectif-objets
  branch: main
publish_mode: editorial_workflow
media_folder: /public/cms/images
locale: fr
site_url: https://collectif-objets.beta.gouv.fr
display_url: https://collectif-objets.beta.gouv.fr
logo_url: https://collectif-objets.beta.gouv.fr/ministere-culture.png
show_preview_links: false
collections:
  - name: articles_presses
    label: Articles de presse
    label_singular: Article de presse
    folder: "/contenus/articles_presse"
    media_folder: "/contenus/articles_presse/images"
    public_folder: "/contenus/articles_presse/images"
    create: true
    slug: "{{year}}_{{month}}_{{slug}}"
    identifier_field: titre
    summary: "{{titre}} ({{date}})"
    sortable_fields: ["titre"]
    fields:
      - { label: "Titre", name: "titre", widget: "string" }
      - { label: "Source", name: "source", widget: "string" }
      - { label: "Date", name: "date", widget: "string" }
      - { label: "Logo", name: "logo", widget: "image" }
      - { label: "URL", name: "url", widget: "string" }
      - { label: "Résumé", name: "resume", widget: "string" }
      - { label: "Corps de l'article", name: "body", widget: "markdown"}
  - name: "fiches"
    label: "Fiches"
    folder: "/contenus/fiches"
    media_folder: "/contenus/fiches/images"
    public_folder: "/contenus/fiches/images"
    create: true
    slug: "{{slug}}"
    identifier_field: titre
    fields:
      - { label: "Titre", name: "titre", widget: "string" }
      - {label: "Corps de la fiche", name: "body", widget: "markdown"}
