test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

ovh:
   service: S3
   access_key_id: <%= Rails.application.credentials.dig(:ovh_storage, :access_key_id) %>
   secret_access_key: <%= Rails.application.credentials.dig(:ovh_storage, :secret_access_key) %>
   region: gra
   bucket: collectif-objets-<%= Rails.env %>
   endpoint: https://s3.gra.cloud.ovh.net

scaleway_defaults: &scaleway_defaults
  service: S3
  endpoint: https://s3.fr-par.scw.cloud
  region: fr-par

scaleway_development:
  <<: *scaleway_defaults
  access_key_id: <%= Rails.application.credentials.dig(:scaleway, :project_co, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:scaleway, :project_co, :secret_access_key) %>
  bucket: collectif-objets-development2

scaleway_staging:
  <<: *scaleway_defaults
  access_key_id: <%= Rails.application.credentials.dig(:scaleway, :project_co, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:scaleway, :project_co, :secret_access_key) %>
  bucket: collectif-objets-staging2

scaleway_production: &scaleway_production
  <<: *scaleway_defaults
  access_key_id: <%= Rails.application.credentials.dig(:scaleway, :project_default, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:scaleway, :project_default, :secret_access_key) %>
  bucket: collectif-objets-production

# scaleway name needs to be preserved for prod because attachments were saved in prod db with this service name
scaleway:
  <<: *scaleway_production
